<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>


    <xacro:property name="chassis_length" value="0.230"/>
    <xacro:property name="chassis_width" value="0.105"/>
    <xacro:property name="chassis_height" value="0.090"/>
    <xacro:property name="chassis_mass" value="0.825"/>
    <xacro:property name="wheel_radius" value="0.0325"/>
    <xacro:property name="wheel_thickness" value="0.025"/>
    <xacro:property name="wheel_mass" value="0.050"/>
    <xacro:property name="wheel_offset_x" value="0.040"/>
    <xacro:property name="wheel_offset_y" value="0.065"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="grey">
        <color rgba="0.4 0.4 0.4 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <material name="yellow">
        <color rgba="1 1 0 1"/>
    </material>


    <!-- BASE LINK -->

    <link name="base_link">

    </link>


    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    
    </link>


    <!-- CHASSIS -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 0"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Grey</material>
    </gazebo>


    <!-- WHEELS -->
    <xacro:macro name="wheel" params="name x y axis rpy_axis">
        <joint name="${name}_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${name}"/>
            <origin xyz="${x} ${y} ${-chassis_height/2 + 0.015}" rpy="${rpy_axis}" />
            <axis xyz="${axis}"/>
        </joint>
        <link name="${name}">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
                </geometry>
                <material name="yellow"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}"/>
                </geometry>
            </collision>
            <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
        </link>
        <gazebo reference="${name}">
            <material>Gazebo/Yellow</material>
        </gazebo>
    </xacro:macro>

    <!-- Front Left Wheel -->
    <xacro:wheel name="front_left_wheel" x="${wheel_offset_x}" y="${wheel_offset_y}" axis="0 0 1" rpy_axis="-${pi/2} 0 0"/>

    <!-- Front Right Wheel -->
    <xacro:wheel name="front_right_wheel" x="${wheel_offset_x}" y="-${wheel_offset_y}" axis="0 0 -1" rpy_axis="${pi/2} 0 0"/>

    <!-- Rear Left Wheel -->
    <xacro:wheel name="rear_left_wheel" x="-${wheel_offset_x}" y="${wheel_offset_y}" axis="0 0 1" rpy_axis="-${pi/2} 0 0"/>

    <!-- Rear Right Wheel -->
    <xacro:wheel name="rear_right_wheel" x="-${wheel_offset_x}" y="-${wheel_offset_y}" axis="0 0 -1" rpy_axis="${pi/2} 0 0"/>


</robot>

